export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const LOGOUT_USER = 'LOGOUT_USER'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';


export const CREATE_PRODUCT_BEGIN = 'CREATE_PRODUCT_BEGIN'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR'

export const GET_PRODUCTS_BEGIN = 'GET_PRODUCTS_BEGIN'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR'

export const GET_SINGLEPRODUCT_BEGIN = 'GET_SINGLEPRODUCT_BEGIN'
export const GET_SINGLEPRODUCT_SUCCESS = 'GET_SINGLEPRODUCT_SUCCESS'
export const GET_SINGLEPRODUCT_ERROR = 'GET_SINGLEPRODUCT_ERROR'

export const GET_AUTHPRODUCTS_BEGIN = 'GET_AUTHPRODUCTS_BEGIN'
export const GET_AUTHPRODUCTS_SUCCESS = 'GET_AUTHPRODUCTS_SUCCESS'
export const GET_AUTHPRODUCTS_ERROR = 'GET_AUTHPRODUCTS_ERROR'

export const UPDATE_PRODUCT_BEGIN = 'UPDATE_PRODUCT_BEGIN'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR'

export const DELETE_PRODUCT_BEGIN = 'DELETE_PRODUCT_BEGIN'



export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

